name: equipment-ci

on:
  pull_request:
  paths:
      - "services/equipment/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/equipment/

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: "11.0.8"
          java-package: jdk
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: test with Maven
        run: mvn clean test -e
